create table mapdetails(city text, country text, population int, latitude float, Longitude float);
select *from mapdetails; 
insert into mapdetails values ("Toy Story","John Lasseter",1995,81);
insert into mapdetails values (2, "A Bug's life","John Lasseter",1998,95);
insert into mapdetails values (3, "Toy Story 2","John Lasseter",1999,93);
insert into mapdetails values (4, "monsters","John Lasseter",2001,95);
insert into mapdetails values (5, "Toy Story1","John Lasseter1",2002,96);
insert into mapdetails values (6, "A Bug's life2","John Lasseter2",2003,97);
insert into mapdetails values (7, "Toy Story 23","John Lasseter3",2004,98);
insert into mapdetails values (8, "monsters1","John Lasseter3",2005,99);
insert into mapdetails values (9, "Toy Story","John Lasseter",1995,81);
insert into mapdetails values (10, "A Bug's life","John Lasseter",1998,95);
insert into mapdetails values (11, "Toy Story 2","John Lasseter",1999,93);
